spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/devlog
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

external:
  github:
    oauth-url: https://github.com/login/oauth/access_token
    api-url: https://api.github.com/user
    headers:
      client-id: ${GITHUB_API_CLIENT_ID}
      client-secret: ${GITHUB_API_CLIENT_SECRET}

jwt:
  secret-key: rkGU45258GGhiolLO2465TFY5345kGU45258GGhiolLO2465TFY5345
  access-token-expiration-ms: 36000
  refresh-token-expiration-ms: 86400000
