spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dldb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
external:
  github:
    oauth-url: https://github.com/login/oauth/access_token
    api-url: https://api.github.com/user
    headers:
      client-id: ${GITHUB_API_CLIENT_ID}
      client-secret: ${GITHUB_API_CLIENT_SECRET}
